In [1]:
import pandas as pd 
import os

In [2]:
pd.set_option('display.max_columns', None)

In [3]:
os.getcwd()

'c:\\Users\\Marcus Bergdahl\\data_science_projects\\FPL_predictions\\artifacts\\fetched_data'

In [4]:
games = pd.read_csv(os.getcwd() + '/get_game_list.csv')
player_details = pd.read_csv(os.getcwd() + '/get_player_details.csv')
player_id = pd.read_csv(os.getcwd() + '/get_player_id.csv')
player_info = pd.read_csv(os.getcwd() + '/get_player_info.csv')
player_name = pd.read_csv(os.getcwd() + '/get_player_name.csv')
round_info = pd.read_csv(os.getcwd() + '/get_round_info.csv')

In [5]:
games.loc[games.finished == False]

,GW,id,home,team_h,away,team_a,finished,kickoff,team_h_score,team_a_score,season_start_year
369,37,319,NEW,14,CRY,6,False,2023-05-25T19:00:00Z,NaN,NaN,22
370,38,371,AVL,1,NaN,20,False,2023-05-28T15:30:00Z,NaN,NaN,22
371,38,372,BOU,2,CHE,5,False,2023-05-28T15:30:00Z,NaN,NaN,22
372,38,373,BHA,4,MUN,13,False,2023-05-28T15:30:00Z,NaN,NaN,22
373,38,374,CRY,6,NFO,15,False,2023-05-28T15:30:00Z,NaN,NaN,22
374,38,375,EVE,7,SOU,16,False,2023-05-28T15:30:00Z,NaN,NaN,22
375,38,376,FUL,8,BRE,3,False,2023-05-28T15:30:00Z,NaN,NaN,22
376,38,377,LIV,11,WHU,18,False,2023-05-28T15:30:00Z,NaN,NaN,22
377,38,378,LEE,10,WOL,19,False,2023-05-28T15:30:00Z,NaN,NaN,22
378,38,379,NEW,14,LEI,9,False,2023-05-28T15:30:00Z,NaN,NaN,22
379,38,380,TOT,17,MCI,12,False,2023-05-28T15:30:00Z,NaN,NaN,22

In [6]:
player_details.loc[player_details.element == 3].sort_values('kickoff_time')

,element,fixture,opponent_team,total_points,was_home,kickoff_time,team_h_score,team_a_score,round,minutes,goals_scored,assists,clean_sheets,goals_conceded,own_goals,penalties_saved,penalties_missed,yellow_cards,red_cards,saves,bonus,bps,influence,creativity,threat,ict_index,starts,expected_goals,expected_assists,expected_goal_involvements,expected_goals_conceded,value,transfers_balance,selected,transfers_in,transfers_out,playername,season_start_year
25801,3,10,13,0,False,2019-08-11T13:00:00Z,0.0,1.0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,55,0,93903,0,0,Sead Kolasinac,19
25802,3,11,5,1,True,2019-08-17T11:30:00Z,2.0,1.0,2,19,0,0,0,0,0,0,0,0,0,0,0,2,2.2,0.3,0.0,0.3,NaN,NaN,NaN,NaN,NaN,55,-32126,61787,416,32542,Sead Kolasinac,19
25803,3,24,10,0,False,2019-08-24T16:30:00Z,3.0,1.0,3,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,54,-8597,56477,1664,10261,Sead Kolasinac,19
25804,3,31,17,1,True,2019-09-01T15:30:00Z,2.0,2.0,4,90,0,0,0,2,0,0,0,0,0,0,0,15,17.0,34.1,13.0,6.4,NaN,NaN,NaN,NaN,NaN,54,-7106,50556,1086,8192,Sead Kolasinac,19
25805,3,49,18,3,False,2019-09-15T15:30:00Z,2.0,2.0,5,90,0,1,0,2,0,0,0,1,0,0,0,21,29.6,23.6,0.0,5.3,NaN,NaN,NaN,NaN,NaN,54,5131,58382,11065,5934,Sead Kolasinac,19
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32,3,329,13,1,False,2023-04-26T19:00:00Z,4.0,1.0,33,59,0,0,0,3,0,0,0,0,0,0,0,5,7.2,10.7,9.0,2.7,1.0,0.02,0.03,0.05,1.85,49,-16389,281705,268,16657,Granit Xhaka,22
33,3,331,6,13,True,2023-05-02T19:00:00Z,3.0,1.0,34,90,0,3,0,1,0,0,0,0,0,0,2,38,49.8,27.3,57.0,13.4,1.0,0.73,0.14,0.87,0.74,48,-7865,273501,1563,9428,Granit Xhaka,22
34,3,346,15,3,False,2023-05-07T15:30:00Z,0.0,2.0,35,90,0,0,1,0,0,0,0,0,0,0,0,17,18.6,14.1,2.0,3.5,1.0,0.00,0.17,0.17,1.30,48,12199,287478,15579,3380,Granit Xhaka,22
35,3,351,5,1,True,2023-05-14T15:30:00Z,0.0,3.0,36,59,0,0,0,1,0,0,0,0,0,0,0,2,3.6,21.9,4.0,3.0,1.0,0.10,0.02,0.12,0.96,48,7176,295114,12485,5309,Granit Xhaka,22
36,3,367,16,2,False,2023-05-20T16:30:00Z,1.0,0.0,37,62,0,0,0,1,0,0,0,0,0,0,0,8,3.4,1.6,0.0,0.5,1.0,0.00,0.01,0.01,0.32,48,5315,300848,12919,7604,Granit Xhaka,22

In [7]:
player_id.loc[player_id.id == 3]

     playername  id
0  Granit Xhaka   3

In [8]:
player_info.loc[player_info.id == 3]

,chance_of_playing_next_round,chance_of_playing_this_round,code,cost_change_event,cost_change_event_fall,cost_change_start,cost_change_start_fall,dreamteam_count,element_type,ep_next,ep_this,event_points,first_name,form,id,in_dreamteam,news,news_added,now_cost,photo,points_per_game,second_name,selected_by_percent,special,squad_number,status,team,team_code,total_points,transfers_in,transfers_in_event,transfers_out,transfers_out_event,value_form,value_season,web_name,minutes,goals_scored,assists,clean_sheets,goals_conceded,own_goals,penalties_saved,penalties_missed,yellow_cards,red_cards,saves,bonus,bps,influence,creativity,threat,ict_index,starts,expected_goals,expected_assists,expected_goal_involvements,expected_goals_conceded,influence_rank,influence_rank_type,creativity_rank,creativity_rank_type,threat_rank,threat_rank_type,ict_index_rank,ict_index_rank_type,corners_and_indirect_freekicks_order,corners_and_indirect_freekicks_text,direct_freekicks_order,direct_freekicks_text,penalties_order,penalties_text,expected_goals_per_90,saves_per_90,expected_assists_per_90,expected_goal_involvements_per_90,expected_goals_conceded_per_90,goals_conceded_per_90,now_cost_rank,now_cost_rank_type,form_rank,form_rank_type,points_per_game_rank,points_per_game_rank_type,selected_rank,selected_rank_type,starts_per_90,clean_sheets_per_90,playername,season_start_year
0,100.0,100.0,84450,0,0,-2,2,1,3,4.5,4.5,2,Granit,4.0,3,False,NaN,2023-04-22T08:30:07.774962Z,48,84450.jpg,3.8,Xhaka,2.6,False,NaN,a,1,3,138,932232,2505,827597,1392,0.8,28.8,Xhaka,2918,5,8,12,35,0,0,0,4,0,0,13,589,647.0,673.3,498.0,182.0,35.0,3.77,3.87,7.64,36.23,60,23,32,25,62,38,41,28,NaN,NaN,2.0,NaN,NaN,NaN,0.12,0.0,0.12,0.24,1.12,1.08,265.0,157.0,42.0,25.0,69.0,30.0,120.0,42.0,1.08,0.37,Granit Xhaka,22
776,100.0,100.0,111457,0,0,-3,3,0,2,3.3,3.1,1,Sead,2.6,3,False,NaN,2020-02-23T18:30:13.672943Z,52,111457.jpg,2.1,Kolasinac,0.5,False,NaN,a,1,3,55,65194,0,134275,0,0.5,10.6,Kolasinac,1694,0,2,4,26,0,0,0,4,0,0,1,331,269.6,182.5,81.0,53.0,NaN,NaN,NaN,NaN,NaN,264,104,215,52,305,98,293,96,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Sead Kolasinac,19
1442,100.0,50.0,41270,0,0,-1,1,0,2,0.3,0.2,0,David,0.0,3,False,NaN,2021-05-02T16:00:26.134258Z,54,41270.jpg,2.0,Luiz Moreira Marinho,0.8,False,NaN,a,1,3,41,77302,0,131045,0,0.0,7.6,David Luiz,1396,1,0,3,20,0,0,0,1,1,0,0,230,250.6,46.7,144.0,43.9,NaN,NaN,NaN,NaN,NaN,264,101,346,119,244,70,310,105,NaN,NaN,4.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,David Luiz Moreira Marinho,20
2155,0.0,0.0,47431,0,0,-2,2,0,3,0.0,0.0,0,Willian,0.0,3,False,Transferred to Corinthians,2021-08-20T09:30:14.065783Z,63,47431.jpg,0.0,Borges Da Silva,0.1,False,NaN,u,1,3,0,914,0,20541,0,0.0,0.0,Willian,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,733,307,733,307,733,307,733,307,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Willian Borges Da Silva,21

In [10]:
round_info.sort_values('deadline_time').loc[round_info['finished'] == False]

,id,name,deadline_time,average_entry_score,finished,data_checked,highest_scoring_entry,deadline_time_epoch,deadline_time_game_offset,highest_score,is_previous,is_current,is_next,cup_leagues_created,h2h_ko_matches_created,chip_plays,most_selected,most_transferred_in,top_element,top_element_info,transfers_made,most_captained,most_vice_captained,season_start_year,chip_name,num_played,top_element_info.id,top_element_info.points
36,37,Gameweek 37,2023-05-20T10:00:00Z,42,False,False,10058448.0,1684576800,0,116.0,False,True,False,True,True,"[{'chip_name': 'bboost', 'num_played': 292434}...",318.0,300.0,324.0,"{'id': 324, 'points': 16}",9940140,318.0,283.0,22,NaN,NaN,NaN,NaN
37,38,Gameweek 38,2023-05-28T14:00:00Z,0,False,False,NaN,1685282400,0,NaN,False,False,True,False,False,[],NaN,NaN,NaN,NaN,0,NaN,NaN,22,NaN,NaN,NaN,NaN